### PR TITLE
Add GH Actions CI

### PR DESCRIPTION
**Pull request by calebeby**

### CODE REVIEW

**Comment by calebeby** [comment]
An idea I had was that in the CI we could clone several open source repos that follow this lint config, and test the new PR build of this lint config against those repos. @spaceninja do you have any ideas of repos we could test against?

**Comment by calebeby** [comment]
Maybe I will copy-paste a few large JS files from other projects into this repo

**Comment by calebeby** [comment]
(I'll leave that separate from this PR)

**Comment by spaceninja** [comment]
Wow, that's a great idea!

Aside from the cloud four pattern library, though, I'm not sure I know any off the top of my head. @tylersticka might have a better idea?

Here's all the results I found on github: https://github.com/search?l=&q=%22%40cloudfour%2Feslint-plugin%22+filename%3Apackage.json&type=Code

**Comment by Paul-Hebert** [comment]
That's a great idea!

**Pull request merged**
