### PR TITLE
Enable some more rules from C4 JS guide and eslint-plugin-node

### LINKED ISSUE #5: Add prefer-destructuring for objects only

### LINKED ISSUE #6: Add prefer-object-spread ESLint rule
See: https://github.com/cloudfour/guides/tree/master/javascript#25-object-shallow-copy

### PR DESCRIPTION
**Pull request by calebeby**
Closes #5, closes #6

I tried adding these rules but decided against it because they are annoying at times:

- `prefer-template`
  For me it seems like string concatenation is easier when there are not any variables being added to the middle of a string:
  ```js
  const name = 'caleb';
  if (plural) {
    return name + 's'
  }
  return name
  ```
- `no-param-reassign`
  Sometimes you know that reassigning to the parameter will not cause undesired side effects, for example:
  ```js
  const prefix = rules =>
  Object.entries(rules).reduce((output, [key, val]) => {
    if (key.includes('/')) key = '@cloudfour/' + key;
    output[key] = val;
    return output;
  }, {});
  ```

What do you think about these rules?

### CODE REVIEW

**Comment by gerardo-rodriguez** [comment]
> `no-param-reassign`
> Sometimes you know that reassigning to the parameter will not cause undesired side effects, for example:

@calebeby Great question! What if we expect all `reduce()` functions to use a standard convention. Perhaps something like `acc` as is shown in the AirBnB rule?

https://github.com/airbnb/javascript/blob/c2f629dcdd98cc16a7a13a7048895a5077759c05/packages/eslint-config-airbnb-base/rules/best-practices.js#L180

**Comment by calebeby** [comment]
Hmm, I'm not sure what the best approach is here. If we allow reassignment for certain parameter names, I think there will still be other cases that we come across in the future where modifying parameters makes more sense than creating a new variable.

**Comment by gerardo-rodriguez** [comment]
> `prefer-template`
> For me it seems like string concatenation is easier when there are not any variables being added to the middle of a string:

I'd prefer consistency. I don't see anything wrong with the following. :)
```js
const name = 'caleb';
if (plural) {
  return `${name}s`;
}
return name
```
Any thoughts @Josh68?

**Comment by calebeby** [comment]
re: string concat
@gerardo-rodriguez sure, we can use template literals, I don't have a strong opinion on this

**Comment by gerardo-rodriguez** [comment]
> Hmm, I'm not sure what the best approach is here. If we allow reassignment for certain parameter names, I think there will still be other cases that we come across in the future where modifying parameters makes more sense than creating a new variable.

@calebeby Totally, this is an interesting scenario. The goal here, as may be obvious, is to try and limit functions with side effects and push toward a more [pure function](https://medium.com/javascript-scene/master-the-javascript-interview-what-is-a-pure-function-d1c076bec976) approach. 

I'm still noodling on what might be the best way to handle this as well. This situation is not the first time [`no-param-reassign` has been discussed alongside `reduce()`](https://github.com/eslint/eslint/issues/8581). 

> Regarding the claim in the OP "// this code is perfectly fine, but violates rule:" - the whole point is that it's not fine, it mutates the accumulator. Certainly that entire reduce operation is pure even though the reducer is not, but there's no way for eslint to know for certain that a) it's Array.prototype.reduce, and b) you've passed a new value in as the initial accumulator.
>
> Lacking that certainty, the proper solution is to enforce no mutation of arguments, or, for you the developer (who does have that certainty) to use an override comment.

At the moment, I only see these options (though there may be more I'm not thinking through?):

1. Not include the `no-param-reassign` ESLint rule and _manually_ enforce via PR reviews.
1. Include the `no-param-reassign` ESLint rule and use the `// eslint-disable-next-line no-param-reassign` comment for specific cases
1. Include the `no-param-reassign` ESLint rule adding the `ignorePropertyModificationsFor` and implementing a standard naming convention

There are pros and cons to each, as always...hmm... 🤔 

Any thoughts on this @Josh68?

**Comment by calebeby** [comment]
Another option would be writing our own modified ESLint rule for `no-param-reassign`, it shouldn't be too hard (I'd be happy to do it 😄).

I think that the best solutions are either disabling the rule and requiring human review, or creating a custom rule.

**Comment by gerardo-rodriguez** [comment]
@calebeby LOL I love it. I'm cool with you looking into writing a custom rule. I'm okay with you timeboxing a couple hours (assuming there are no pressing client needs) too look into this. Otherwise, we can fall back to depending on human review, which is fine. 😉

**Pull request merged**
